# Generated by Django 5.1.7 on 2025-04-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('seminar', 'Seminar'), ('sports', 'Sports'), ('music', 'Music'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.place')),
            ],
        ),
    ]
