# Generated by Django 5.1.7 on 2025-04-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('dorm', 'Dorm'), ('library', 'Library'), ('lab', 'Lab'), ('classroom', 'Classroom'), ('office', 'Office'), ('cafe', 'Cafe'), ('fun', 'Fun')], max_length=20),
        ),
        migrations.CreateModel(
            name='NavigationInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_en', models.CharField(max_length=255)),
                ('instruction_am', models.CharField(blank=True, max_length=255, null=True)),
                ('step_order', models.PositiveIntegerField(help_text='Order of this instruction in a route')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_instructions', to='api.place')),
            ],
        ),
    ]
